# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_DTB_RT2880_EVAL)	+= rt2880_eval.dtb
dtb-$(CONFIG_DTB_RT305X_EVAL)	+= rt3052_eval.dtb
dtb-$(CONFIG_DTB_RT3883_EVAL)	+= rt3883_eval.dtb
dtb-$(CONFIG_DTB_MT7620A_EVAL)	+= mt7620a_eval.dtb
dtb-$(CONFIG_DTB_OMEGA2P)	+= omega2p.dtb
dtb-$(CONFIG_DTB_VOCORE2)	+= vocore2.dtb

dtb-$(CONFIG_DTB_UBNT_EDGEROUTER_X_SFP)	+= mt7621_ubnt_edgerouter-x-sfp.dtb
dtb-$(CONFIG_DTB_UBNT_EDGEROUTER_X)	+= mt7621_ubnt_edgerouter-x.dtb
dtb-$(CONFIG_DTB_MTC_WR1201)		+= mt7621_mtc_wr1201.dtb

obj-$(CONFIG_BUILTIN_DTB)	+= $(addsuffix .o, $(dtb-y))